
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package test;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int id = 9;
  public static final int puntocoma = 7;
  public static final int EOF = 0;
  public static final int tipoVar = 3;
  public static final int numero = 8;
  public static final int error = 1;
  public static final int llaveIzq = 4;
  public static final int tclass = 2;
  public static final int llaveDer = 5;
  public static final int igual = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tclass",
  "tipoVar",
  "llaveIzq",
  "llaveDer",
  "igual",
  "puntocoma",
  "numero",
  "id"
  };
}

