package test;

import analisisLexico.*;
import java_cup.runtime.ComplexSymbolFactory.ComplexSymbol;
import analisisLexico.Entorno.Tipo;
import analisisLexico.Entorno.GlobalVariables;

terminal    String			tclass, tipoVar, llaveIzq, llaveDer;
terminal    String			igual, puntocoma;
terminal	String			numero;
terminal	String			id;

non terminal				programa;
non terminal				clase;
non terminal				cuerpo;
non terminal				elemento;
non terminal				asignacion;

start with programa;

programa 	::= 							{: GlobalVariables.entraBloque(); :}
				clase:c 					{: GlobalVariables.saleBloque(); :}
			;
			
clase		::=	tclass:t id:i llaveIzq  	{: GlobalVariables.entraBloque(); :}
				cuerpo:c 					{: GlobalVariables.saleBloque(); :}
				llaveDer
			;
			
cuerpo 		::= cuerpo:c elemento:e 		{: :}
			|								{: :}
			;
			
elemento 	::= asignacion:a 									{: :}
			| clase:c											{: :}
			;
			
asignacion 	::= tipoVar:t id:i igual numero:n puntocoma 		{: GlobalVariables.asignaID(i,t); :}
			| tipoVar:t id:i puntocoma 							{: GlobalVariables.asignaID(i,t); :}
			| id:i igual numero:n puntocoma 					{: /* -> no es una declaración nueva <- GlobalVariables.asignaID(i,t); */ :}
			;